export enum CharacterState {
  noclip = 1 << 0,
  doubleJump = 1 << 1,
  isInvisible = 1 << 2,
  noHands = 1 << 3,
  noEyes = 1 << 4,
  noBody = 1 << 5,
  devilHorns = 1 << 6,
  goldenHalo = 1 << 7,
  isFrozen = 1 << 11,
  isCursed = 1 << 12,
  isDuctaped = 1 << 13,
  haveCigar = 1 << 14,
  isShining = 1 << 15,
  isZombie = 1 << 16,
  isHitByLava = 1 << 17,
  haveHauntedShadows = 1 << 18,
  haveGeigerRadiation = 1 << 19,
  spotlight = 1 << 20,
  isEgged = 1 << 21,
  havePineappleFlag = 1 << 22,
  haveFlyingPineapple = 1 << 23,
  haveSuperSupporterName = 1 << 24,
  haveSuperPineapple = 1 << 25
}